### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by theAkito** [zhaojh329/libumqtt#8]
I am trying to implement libumqtt within a server written in [Nim](https://nim-lang.org/). I am not familiar with C, but I know how to use C libraries within Nim. To implement this type of libraries correctly, I need documentation on how the library works and what the procedures do in what way. Is there a way to generate documentation from this library or is there documentation I have missed, yet?

**Comment by zhaojh329** [comment]
Please reference the example.

**Comment by theAkito** [comment]
@zhaojh329  Well, I want the server to auto-subscribe to a topic with a specific name. Then, after successful subscription, I want the server to listen for incoming requests originating from the topic. So, taking this case as an example, what do I need to call from the library to make this happen?

**Comment by zhaojh329** [comment]
libumqtt is a client library.

**Comment by theAkito** [comment]
@zhaojh329 
Every subscriber is a client, I assume? The main purpose for it being a server is that it runs all the time. Technically, it is still a client, since it is supposed to **receive** messages and not send them.

Here is what is supposed to happen:
1. Server listening.
2. Server gets message "print this comment".
3. Server prints the comment.
4. Done.

**Comment by zhaojh329** [comment]
Please reference the example.
https://github.com/zhaojh329/libumqtt/tree/master/example
